---
title: "Risk Benefit Analysis for Toast-USB Launch"
author: "Allison McCarty, Nicholas Mobley, Nijia Ke"
date: "4/1/2021"
output: html_document
---

The sustained popularity of toast as an American breakfast food coupled with recent Millennial and Gen-Z trends driving the popularity of gourmet toast has created an exciting opportunity for innovation that combines technology and toast. Thus, our client, Toast Co., created the Toast-USB, which would allow amateurs and toast connoisseurs alike to create culinary-grade toast straight from their computer. The goal of this investigation was to perform a statistical analysis to help Toast Co. to make informed, data-driven decisions regarding the launch of Toast-USB.  After an in-depth investigation, we estimated that the favorable response rate for the Toast-USB was 12.14%, which was under the 24.13% benchmark that is required to break-even. Based on this result, we do not recommend that Toast Co. proceed with the launch of the Toast-USB for the general population.  Instead, Toast Co. could consider re-strategizing marketing to target niche demographic groups.

The data for this investigation comes from two studies.  The first study includes data from a market analysis conducted by Toast Co. from five metropolitan areas (Toronto, ON; New York City, NY, Philadelphia, PA; Dallas, TX, and San Francisco, CA).  The second study was conducted by our firm’s DOE in the same five metropolitan areas to determine the likelihood of success of the Toast-USB.  Toast Co.’s market analysis contained 421 observations of 8 variables, while the DOE’s campaign contained 45,211 observations of 17 variables.  We performed baseline data processing on data from the second sample, including performing a single imputation of the median to replace the missing values for the variables representing balance, campaign, age, and duration.  The two samples both contained data on age, balance, job, education, marital status, mortgage, and primary phone variables which could be used to synthesize the key findings from the first and second study and perform a risk-benefit analysis on continuation of the campaign.

The goal of exploratory data analysis and definitive statistical analysis was to address three specific aims:

1.	Compare the demographic and campaign-specific features from the two samples quantitatively and qualitatively.


2.	Make a binary (Y/N) recommendation regarding launch of the product based on a selection of significant demographic predictors and logistic modeling.


3.	Determine an MSRP that will maximize revenue for the product.


In the initial analysis, we compared the demographic features of the first and second study. We obtained distribution plots and 95% confidence intervals for the numeric variables for the numerical variables common in both studies.  Next, we compared the categorical variables common in both studies, including job, education, marital status, mortgage and primary phone.  The results of the comparison of the two studies, both for the numerical and categorial predictors, suggest that samples in the two studies are unlikely from the same population.  We found individuals who are white, male, and have high levels of education are overrepresented in the first study, while individuals with a mortgage are underrepresented in the first study. Additionally, we found that individuals with no personal loan are overrepresented in the second study.  To confirm these conclusions, we performed a likelihood ratio test to verify that there is significant evidence that response to buy the product are associated with all the demographic variables in both studies.  The likelihood ratio tests confirmed that the demographic composition of the first study was significantly different from the demographic composition of the randomized sample from the second study.

Next, we performed further exploratory analysis on the data from the second study to gain insights on which demographic variables would have a meaningful effect on the favorable response rate.  We found that age, personal loan status, default status and education were key demographic features of interest for the marketing campaign.  We generated 15 logistic model representing every combination of the four aforementioned variables regressed on favorable response.  Based on cross validation using maximum likelihood ratio, the model including age, personal loan status, and education was selected as the best model for this data.

Next, we performed a simulation using the model to predict the favorable response rate to the toaster.  Unfortunately, the estimated response rate for this sample was 12.14%, which was under the 24.13% benchmark that is required to break-even, and further below the 50.36% favorable response rate estimated by the first study.  Based on this result, we recommend against the launch of the Toast-USB, and instead suggest that Toast Co. consider a launch that targets the niche market of older, highly-educated demographic groups.  In addition, Toast Co. could also reevaluate their business strategy by making updates to the product itself, including adding more functional features, updating the aesthetic design, or improving the software systems to the product with this demographic group in mind.

Lastly, we performed a quantitative analysis to determine the MSRP for the Toast-USB to maximize revenue for the company.  To do this, we performed a simulation using the probability that the individual would purchase the product calculated from the logistic model and the price that the individual cited that they were willing to pay. Using this process, we determined that the optimal price for this product is 46 USD, which would generate an estimated revenue of 60,000 USD.
